import { baseApi } from "../api/baseApi"; // Ensure baseApi is correctly imported

const AllProjectsApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        allProjects: builder.query({
            query: () => ({
                url: '/superuser/all-skills',
                method: 'GET',
            })
        })
    })
})

// Export the hook generated by RTK Query
export const { useAllProjectsQuery } = AllProjectsApi; 
