import { baseApi } from "../api/baseApi"; // Ensure baseApi is correctly imported

const superUserApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        superUser: builder.query({
            query: () => ({
                url: '/superuser/skills',
                method: 'GET',
            })
        })
    })
})

// Export the hook generated by RTK Query
export const { useSuperUserQuery } = superUserApi; 

export default superUserApi;